inputs:
  port:
    description: 'port for app'

  environment:
    description: 'app environment'

runs:
  using: "composite"
  steps:
    - name: run command
      shell: zsh {0}
      run: exec "$SHELL" 
      working-directory: ./python-greetings

    - name: run command
      shell: zsh {0}
      run: pm2 delete greetings-app-${{ inputs.environment }} & set "errorlevel=O"
      working-directory: ./python-greetings

    - name: run command
      shell: zsh {0}
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
      working-directory: ./python-greetings


