inputs:
  port:
    description: 'port for app'

  environment:
    description: 'app environment'

runs:
  using: "composite"
  steps:

    - name: checkout remote
      uses: actions/checkout@3.5.2
      with:
        repository: 'mtararujs/python-greetings' 
      shell: sh
      
    - name: run command
      shell: sh
      run: pm2 delete greetings-app-${{ inputs.environment }} & set "errorlevel=O"

    - name: run command
      shell: sh
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}


