# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  install-pip-deps:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
        with: 
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'
      - name: Output text
        run: echo Installing all required depdendencies..
      - name: installing
        working-directory: ./python-greetings
        run: pip install -r requirements.txt

  deploy-to-dev:
      runs-on: self-hosted
      needs: [install-pip-deps]
      steps:
        - uses: actions/checkout@v3.5.2 
        - uses: ./.github/actions/deploy
          with:
            port: 7001
            environment: 'dev'

        - name: Output text
          run: echo Deploying to dev..

  tests-on-dev:
      runs-on: self-hosted
      needs: [deploy-to-dev]
      steps:
        - uses: actions/checkout@v3.5.2
        - uses: ./.github/actions/test
          with:
            environment: 'dev'

        - name: Output text
          run: echo Testing on dev..

  deploy-to-staging:
      runs-on: self-hosted
      needs: [tests-on-dev]
      steps:
        - uses: actions/checkout@v3.5.2
        - uses: ./.github/actions/deploy
          with:
            port: 7002
            environment: 'staging'

        - name: Output text
          run: echo Deploying to staging..          

  tests-on-staging:
      runs-on: self-hosted
      needs: [deploy-to-staging]
      steps:
        - uses: actions/checkout@v3.5.2
        - uses: ./.github/actions/test
          with:
              environment: 'staging'

        - name: Output text
          run: echo Testing on staging..   

  deploy-to-preprod:
      runs-on: self-hosted
      needs: [tests-on-staging]
      steps:
        - uses: actions/checkout@v3.5.2
        - uses: ./.github/actions/deploy
          with:
            port: 7003
            environment: 'dev'

        - name: Output text
          run: echo Deploying to preprod..  

  tests-on-preprod:
      runs-on: self-hosted
      needs: [deploy-to-preprod]
      steps:
        - uses: actions/checkout@v3.5.2
        - uses: ./.github/actions/test
          with:
              environment: 'preprod'

        - name: Output text
          run: echo Testing on preprod..                      

  deploy-to-prod:
      runs-on: self-hosted
      needs: [tests-on-preprod]
      steps:
        - uses: actions/checkout@v3.5.2
        - uses: ./.github/actions/deploy
          with:
            port: 7004
            environment: 'prod' 

        - name: Output text
          run: echo Deploying to prod..

  tests-on-prod:
      runs-on: self-hosted
      needs: [deploy-to-prod]
      steps:
        - uses: actions/checkout@v3.5.2
        - uses: ./.github/actions/test
          with:
              environment: 'prod'

        - name: Output text
          run: echo Testing on prod..          
